export default [
    {
        id:'1',
        name:'订单管理',
        children:[
            {
                name:'处理订单',
                url:'/nav/DoingOrder'
            },
            {
                name:'进行订单',
                url:'/nav/DoingOrder'
            },
            {
                name:'完成订单',
                url:'/nav/DoneOrder'
            }
        ]
    },
    {
        id:'2',
        name:'用户管理',
        children:[
            {
                name:'用户列表',
                url:'/nav/Customer'
            }
        ]
    },
    {
        id:'3',
        name:'车辆管理',
        children:[
            {
                name:'车辆列表',
                url:'/nav/Vehicle'
            }
        ]
    },
    {
        id:'4',
        name:'计费管理',
        children:[
            {
                name:'价格列表',
                url:'/nav/Vehicle'
            }
        ]
    },
    {
        id:'5',
        name:'信息管理',
        children:[
            {
                name:'个人信息',
                url:'/nav/Vehicle'
            }
        ]
    }
]